### ISSUE TITLE
[Variadic views] Did adding hwloc support break them?

### ISSUE THREAD

**Issue by nmnobre** [a-pop/OpenStream#14]
Somewhere between commit 09d4556 and commit 9ed7ab7, we broke support for variadic views.

The following OpenStream program reproduces the problem: 
```c
#include <stdio.h>
#include <string.h>

#define N 5

int main(int argc, char const *argv[])
{
	double s[N] __attribute__ (( stream ));
	double win[N][1];

	#pragma omp task output (s << win[N][1]) 
	{
		for (size_t i = 0; i < N; i++)	
			win[i][0]=i;
	}

	#pragma omp task input (s >> win[N][1])
	{
		for (size_t i = 0; i < N; i++)	
			printf("%f \n",win[i][0]);
	}
	
	#pragma omp taskwait
}
```

**Comment by Syllo** [comment]
The root of the problem lies with the introduction of the USE_BROADCAST_TABLES option, removing unused code when the option is disabled.

I think that something is broken with the `next` array pointer arithmetic between the generated compiler code and the library.
The rational behind that is that with the patch applied, adding a dummy field, or keeping the broadcast table pointer, into the `struct wstream_df_view` of libworkstream fixes the segfault, even though everything else related to the broadcast table is not generated.

To reproduce checkout to commit 7a7a23306d55f6658a1de6bf6b3a006702aa73d9, which is right after the gcc9 port and apply the following patch [broadcast_table_option.diff.txt](https://github.com/pepperpots/OpenStream/files/4878885/broadcast_table_option.diff.txt)
